<?php

namespace OC\BookingBundle\Repository;

/**
 * BookingformRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingformRepository extends \Doctrine\ORM\EntityRepository
{
}
