<?php

namespace OC\BookingBundle\Repository;

/**
 * BookingdayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingdayRepository extends \Doctrine\ORM\EntityRepository
{
}
