oc_booking_homepage:
    path:     /museedulouvre.fr
    defaults: { _controller: OCBookingBundle:Home:index }

oc_booking_form:
    path:    /museedulouvre.fr/billeterie
    defaults: { _controller: OCBookingBundle:Bookingform:form }

oc_payment_form:
    path:    /museedulouvre.fr/paiement
    defaults: { _controller: OCBookingBundle:Paymentform:payment }